### ISSUE TITLE
vault HA pods not starting when including this extra container

### ISSUE THREAD

**Issue by pksurferdad** [flyte/docker-vault-cert-reloader#1]
i set up a new vault listener with a cert from lets encrypt

```
extraVolumes:
  - type: secret
    name: vault-server-tls-letsencrypt
  - type: secret
    name: vault-server-tls

# listener for the vault UI
        listener "tcp" {
          address                  = "0.0.0.0:8202"
          tls_key_file             = "/vault/userconfig/vault-server-tls-letsencrypt/tls.key"
          tls_cert_file            = "/vault/userconfig/vault-server-tls-letsencrypt/tls.crt"
          tls_disable = false
          tls_disable_client_certs = "true"
        }
```

but after including this config in the helm chart under the server node, the vault nodes would not start up.  i was thinking that maybe the issue was the mountPath should be different? . i'm running vault 1.11

```
  extraContainers:
    - name: cert-watcher
      image: ghcr.io/flyte/docker-vault-cert-reloader:1.0.4
      args:
        - /var/run/secrets/vault-server-tls-letsencrypt/tls.crt
      volumeMounts:
        - name: vault-server-tls-letsencrypt
          mountPath: /var/run/secrets/vault-server-tls-letsencrypt
          readOnly: true
  shareProcessNamespace: true
```
